### ISSUE TITLE
ProEXR Layer Export Crash in Windows Photoshop CC 2015.5

### ISSUE THREAD

**Issue by jlang** [fnordware/ProEXR#3]
Hi fnordware,

Launching the ProEXR Layer Export (v1.93) results in an "Adobe Photoshop CC 2015.5 has stopped working" crash for Adobe Photoshop CC 2015.5. I'm running photoshop on Windows 10.  

Steps to reproduce:
1. Create a new file using the default prefs
2. Create a new layer
3. Change image mode to 32 bits/channel
4. File > Export  > ProEXR Layer Export results in the crash

Were the latest updates supported in Photoshop CC 2015+? This option was previously working with ProEXR 1.92 with a purchased license.

Thanks!

**Comment by fnordware** [comment]
Whoops! It's back as of 39bed168809e5d293cbb4065e1ddfabc82b6feed
