### ISSUE TITLE
Cryptomatte - "Enter" presses cancel instead of "OK"

### ISSUE THREAD

**Issue by jonahfriedman** [fnordware/ProEXR#4]
When you open the Cryptomatte effect in the Effects Controls tab, and you click on "Selection", a little window pops up with "Layer", "Selection", and "Manifest. 

In that window, if you make changes to "Selection" and press enter, they take effect just fine. However, if your text cursor is under "Layer" and you press enter, it closes without your changes. 

This is on Windows and After Effects CC 2018.

**Comment by fnordware** [comment]
This should be fixed in beta 3 with 5767bf4c80e7166f56a3f32965a2b505ede9328b. Try it!
